# Generated by Django 5.2.1 on 2025-06-04 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Тварина', 'verbose_name_plural': 'Тварини'},
        ),
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='polls.category'),
        ),
    ]
